In [1]:
import pandas as pd

In [2]:
dataset1=pd.read_csv("deliveries.csv")
dataset=pd.read_csv("matches.csv")
dataset1

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [3]:
total_score=dataset1.groupby(['match_id','inning']).sum()['total_runs'].reset_index()
total_score

      match_id  inning  total_runs
0            1       1         207
1            1       2         172
2            2       1         184
3            2       2         187
4            3       1         183
...        ...     ...         ...
1523     11413       2         170
1524     11414       1         155
1525     11414       2         162
1526     11415       1         152
1527     11415       2         157

[1528 rows x 3 columns]

In [4]:
total_score = total_score[total_score['inning']==1]

In [5]:
total_score

      match_id  inning  total_runs
0            1       1         207
2            2       1         184
4            3       1         183
6            4       1         163
8            5       1         157
...        ...     ...         ...
1518     11347       1         143
1520     11412       1         136
1522     11413       1         171
1524     11414       1         155
1526     11415       1         152

[756 rows x 3 columns]

In [6]:
match=dataset.merge(total_score[['match_id','total_runs']],left_on='id',right_on='match_id')

In [7]:
 match['team1'].unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [8]:
teams = ['Sunrisers Hyderabad', 'Mumbai Indians', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders','Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 
       'Delhi Capitals']

In [9]:
match['team1']=match['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match['team2']=match['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

match['team1']=match['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match['team2']=match['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

In [10]:
match = match[match['team1'].isin(teams)]
match = match[match['team2'].isin(teams)]

In [11]:
match.head(2)

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,207
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,157

In [12]:
match.shape

(641, 20)

In [13]:
#we are removing matches where duck wearth lewis is available 
# 1 = yes , 0 = no
match=match[match['dl_applied']==0]

In [14]:
match.shape

(626, 20)

In [15]:
match=match[['match_id','city','winner','total_runs']]

In [16]:
final=match.merge(dataset1,on='match_id')

In [17]:
final.head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder
0,1,Hyderabad,Sunrisers Hyderabad,207,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,Hyderabad,Sunrisers Hyderabad,207,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,Hyderabad,Sunrisers Hyderabad,207,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,Hyderabad,Sunrisers Hyderabad,207,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,Hyderabad,Sunrisers Hyderabad,207,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [18]:
final = final[final['inning'] == 2]

In [19]:
final.head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,0,0,0,1,0,1,NaN,NaN,NaN
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
127,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
128,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,0,0,0,2,0,2,NaN,NaN,NaN
129,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [20]:
final.shape

(72413, 24)

In [21]:
final.head(2)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,0,0,0,1,0,1,NaN,NaN,NaN
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [22]:
final['total_runs_y']

125       1
126       0
127       0
128       2
129       4
         ..
149573    1
149574    2
149575    1
149576    2
149577    0
Name: total_runs_y, Length: 72413, dtype: int64

In [23]:
final['total_runs_y'] = final['total_runs_y'].astype('int64')

In [24]:
final['total_runs_y']

125       1
126       0
127       0
128       2
129       4
         ..
149573    1
149574    2
149575    1
149576    2
149577    0
Name: total_runs_y, Length: 72413, dtype: int64

In [25]:
final['current_score']=final.groupby('match_id')['total_runs_y'].cumsum()

In [26]:
final['runs_left'] = final['total_runs_x']-final['current_score']

In [27]:
final['balls left'] = 120 - (final['over']*6 + final['ball'])

In [28]:
final.head(2)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls left
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,1,0,1,NaN,NaN,NaN,1,206,113
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,NaN,NaN,NaN,1,206,112

In [29]:
final['player_dismissed']=final["player_dismissed"].fillna(0)

In [30]:
final.head(3)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls left
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,1,0,1,0,NaN,NaN,1,206,113
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,0,NaN,NaN,1,206,112
127,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,0,NaN,NaN,1,206,111

In [31]:
final['player_dismissed']=final['player_dismissed'].apply(lambda x : x if x == 0 else 1 )
final['player_dismissed'] = final['player_dismissed'].astype('int64')

In [32]:
wickets = final.groupby('match_id')['player_dismissed'].cumsum().values
final['wicket'] = 10 - wickets

In [33]:
final.head(3)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls left,wicket
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,1,0,1,0,NaN,NaN,1,206,113,10
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,NaN,NaN,1,206,112,10
127,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,NaN,NaN,1,206,111,10

In [34]:
final.tail()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls left,wicket
149573,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,1,0,1,0,NaN,NaN,152,0,-2,5
149574,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,2,0,2,0,NaN,NaN,154,-2,-3,5
149575,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,1,0,1,1,run out,KH Pandya,155,-3,-4,4
149576,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,2,0,2,0,NaN,NaN,157,-5,-5,4
149577,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,1,lbw,NaN,157,-5,-6,3

In [35]:
# current run rate = runs/overs
final['crr']=(final['current_score']*6)/(120 - final['balls left'])

In [36]:
#rrr 
final['rrr'] = (final['runs_left']*6)/final['balls left']

In [37]:
def result(row):
    return 1 if row['batting_team'] == row['winner'] else 0

In [38]:
final['result']=final.apply(result,axis=1)

In [39]:
final1 =final[['batting_team','bowling_team','city','runs_left','balls left','wicket','total_runs_x','crr','rrr','result']]

In [40]:
final1

,batting_team,bowling_team,city,runs_left,balls left,wicket,total_runs_x,crr,rrr,result
125,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,206,113,10,207,0.857143,10.938053,0
126,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,206,112,10,207,0.750000,11.035714,0
127,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,206,111,10,207,0.666667,11.135135,0
128,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,204,110,10,207,1.800000,11.127273,0
129,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,200,109,10,207,3.818182,11.009174,0
...,...,...,...,...,...,...,...,...,...,...
149573,Chennai Super Kings,Mumbai Indians,Hyderabad,0,-2,5,152,7.475410,-0.000000,0
149574,Chennai Super Kings,Mumbai Indians,Hyderabad,-2,-3,5,152,7.512195,4.000000,0
149575,Chennai Super Kings,Mumbai Indians,Hyderabad,-3,-4,4,152,7.500000,4.500000,0
149576,Chennai Super Kings,Mumbai Indians,Hyderabad,-5,-5,4,152,7.536000,6.000000,0
149577,Chennai Super Kings,Mumbai Indians,Hyderabad,-5,-6,3,152,7.476190,5.000000,0

In [41]:
skdjfhklas

NameError: name 'skdjfhklas' is not defined

In [ ]:
final1=final1.sample(final.shape[0])

In [ ]:
final1.dropna(inplace=True)

In [ ]:
final1.head(3)

In [ ]:
final1 = final1[final1['balls left']!=0]

In [ ]:
x = final1.iloc[:,:-1]
y = final1.iloc[:,-1]

In [ ]:
final1['city'].unique()

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder
trf = ColumnTransformer(
    [('trf', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])],
    remainder='passthrough'
)

In [ ]:
help(ColumnTransformer)

In [ ]:
from sklearn.linear_model import LogisticRegression 
from sklearn.pipeline import Pipeline

In [ ]:
pipe = Pipeline(steps=[('step1',trf),('step2',LogisticRegression(solver='liblinear'))])

In [ ]:
pipe.fit(x_train,y_train)
pipe.score(x_train,y_train)*100 , pipe.score(x_test,y_test)*100

In [ ]:
y_pred = pipe.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
import numpy as np
accuracy_score(y_test,y_pred)*100

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB
from sklearn.svm import SVC

In [ ]:
dt = DecisionTreeClassifier()
mu = MultinomialNB()
be = BernoulliNB()
ga = GaussianNB()
sv = SVC()

In [ ]:
pipe2 = Pipeline(steps=[('step1',trf),('step2',DecisionTreeClassifier())])
pipe3 = Pipeline(steps=[('step1',trf),('step2',MultinomialNB())])
pipe4 = Pipeline(steps=[('step1',trf),('step2',SVC())])

In [ ]:
pipe2.fit(x_train,y_train)
pipe2.score(x_train,y_train)*100 , pipe2.score(x_test,y_test)*100

In [ ]:
def get_user_input():
    batting_team = input("Enter the batting team: ")
    bowling_team = input("Enter the bowling team: ")
    city = input("Enter the city: ")
    current_over = int(input("Enter the current over: "))
    
    overs_left = 20 - current_over 
    
    # Calculating derived inputs
    balls_left = overs_left * 6
    current_score = int(input("Enter the current score: "))
    target_score = int(input("Enter the target score: "))
    runs_left = target_score - current_score
    wic = int(input("Enter the number of wickets down: "))
    wickets_left = 10 - wic
    
    # Calculating crr and rrr
    crr = (current_score * 6) / (120 - balls_left)
    rrr = (runs_left * 6) / balls_left
    
    # Prepare the dataframe
    data = {
        'batting_team': [batting_team],
        'bowling_team': [bowling_team],
        'city': [city],
        'runs_left': [runs_left],
        'balls left': [balls_left],
        'wicket': [wickets_left],
        'total_runs_x': [target_score],
        'crr': [crr],
        'rrr': [rrr],
        'overs_left':[overs_left]
    }
    
    return pd.DataFrame(data)

def predict_match_outcome(pipe):
    
    new_match_df = get_user_input()
    
    # Predict probabilities using the trained pipeline
    result = pipe2.predict_proba(new_match_df)
    new_match_df['lose'] = np.round(result.T[0] * 100, 1)
    new_match_df['win'] = np.round(result.T[1] * 100, 1)
    #new = user
    #result = pipe.predict_prob(new)
    #new['loss'] = np.round(result.T[0] * 100,1)
    #new['win'] = np.round(result.T[1]*100,1)
    
   
    # Display the results
    print(new_match_df[['balls left','runs_left']])
    print(new_match_df[['overs_left','crr', 'rrr', 'win','lose']])
    
#predict_match_outcome(pipe)

In [ ]:
teams = ['Sunrisers Hyderabad', 'Mumbai Indians', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders','Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 
       'Delhi Capitals']

In [ ]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

In [ ]:
pipe4.fit(x_train,y_train)
pipe4.score(x_train,y_train)*100 , pipe4.score(x_test,y_test)*100

In [ ]:
pipe5 = Pipeline(steps=[('step1',trf),('step2',BernoulliNB())])

In [ ]:
pipe5.fit(x_train,y_train)
pipe5.score(x_train,y_train)*100 , pipe5.score(x_test,y_test)*100

In [ ]:
pipe6 = Pipeline(steps=[('step1',trf),('step2',DecisionTreeClassifier(max_depth=7))])

In [ ]:
pipe6.fit(x_train,y_train)
pipe6.score(x_train,y_train)*100 , pipe6.score(x_test,y_test)*100

In [ ]:
predict_match_outcome(pipe6)